import React, { useState } from 'react';
import {
  Users,
  UserPlus,
  Copy,
  Check,
  Trash2,
  Phone,
  MapPin,
  KeyRound,
  Shield,
  Briefcase,
  Search,
  ExternalLink,
  Sparkles,
  CheckCircle2,
} from 'lucide-react';
import { Customer } from '../types';

interface CustomerManagementProps {
  customers: Customer[];
  onCreateCustomer: (customerData: any) => Promise<any>;
  onDeleteCustomer: (id: string) => Promise<void>;
  onSelectCustomerProjects: (customerId: string) => void;
}

export const CustomerManagement: React.FC<CustomerManagementProps> = ({
  customers,
  onCreateCustomer,
  onDeleteCustomer,
  onSelectCustomerProjects,
}) => {
  const [showAddModal, setShowAddModal] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Form states
  const [name, setName] = useState('');
  const [username, setUsername] = useState('');
  const [phone, setPhone] = useState('');
  const [address, setAddress] = useState('');
  const [notes, setNotes] = useState('');
  const [customPassword, setCustomPassword] = useState('');
  const [createdResult, setCreatedResult] = useState<{ username: string; password: string; name: string } | null>(null);
  const [submitting, setSubmitting] = useState(false);

  // Calculate current solar year (e.g. 1404 / 1405)
  const solarYear = (() => {
    try {
      const formatter = new Intl.DateTimeFormat('fa-IR-u-ca-persian', { year: 'numeric' });
      const f = formatter.format(new Date());
      const pToE: Record<string, string> = {
        '۰': '0', '۱': '1', '۲': '2', '۳': '3', '۴': '4',
        '۵': '5', '۶': '6', '۷': '7', '۸': '8', '۹': '9',
      };
      const en = f.replace(/[۰-۹]/g, (w) => pToE[w] || w).replace(/[^0-9]/g, '');
      const parsed = parseInt(en, 10);
      return isNaN(parsed) ? 1405 : parsed;
    } catch {
      return 1405;
    }
  })();

  const cleanUser = username.trim().toLowerCase().replace(/\s+/g, '');
  const autoGeneratedPassword = `${solarYear}${cleanUser || 'username'}`;

  const handleCopyCredentials = (c: Customer) => {
    const text = `سلام و احترام جناب/سرکار ${c.name}
مشخصات ورود به سامانه آنلاین رهگیری ساخت گاوصندوق:
🌐 نام کاربری: ${c.username}
🔑 کلمه عبور: ${c.password || `${solarYear}${c.username}`}

جهت مشاهده عکس مراحل ساخت، برشکاری، بتن‌ریزی و وضعیت پیشرفت سفارش می‌توانید وارد سامانه شوید.`;

    navigator.clipboard.writeText(text);
    setCopiedId(c.id);
    setTimeout(() => setCopiedId(null), 3000);
  };

  const handleFormSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim() || !username.trim() || !phone.trim()) {
      alert('لطفاً نام، نام کاربری و شماره تماس را وارد کنید.');
      return;
    }

    setSubmitting(true);
    try {
      const res = await onCreateCustomer({
        name: name.trim(),
        username: cleanUser,
        phone: phone.trim(),
        address: address.trim(),
        notes: notes.trim(),
        customPassword: customPassword.trim(),
      });

      setCreatedResult({
        name: name.trim(),
        username: cleanUser,
        password: res?.generatedPassword || customPassword || `${solarYear}${cleanUser}`,
      });

      // Clear form
      setName('');
      setUsername('');
      setPhone('');
      setAddress('');
      setNotes('');
      setCustomPassword('');
    } catch (err: any) {
      alert(err.message || 'خطا در ثبت مشتری');
    } finally {
      setSubmitting(false);
    }
  };

  const filtered = customers.filter(
    (c) =>
      c.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      c.username.toLowerCase().includes(searchQuery.toLowerCase()) ||
      c.phone.includes(searchQuery)
  );

  return (
    <div className="space-y-6">
      {/* Top action header */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 sm:p-6 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-100 flex items-center gap-2">
            <Users className="w-5 h-5 text-red-500" />
            <span>مدیریت مشتریان و ایجاد دسترسی رهگیری</span>
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            تعریف خریداران با تولید خودکار رمز عبور بر پایه سال شمسی ({solarYear} + نام‌کاربری)
          </p>
        </div>

        <button
          id="open-create-customer-btn"
          onClick={() => {
            setCreatedResult(null);
            setShowAddModal(true);
          }}
          className="bg-red-600 hover:bg-red-700 text-white font-bold px-4 py-2.5 rounded-xl text-xs sm:text-sm flex items-center gap-2 shadow-md shadow-red-950/40 transition-all cursor-pointer"
        >
          <UserPlus className="w-4 h-4" />
          <span>تعریف مشتری جدید</span>
        </button>
      </div>

      {/* Search and stats bar */}
      <div className="flex flex-col sm:flex-row gap-3 items-center justify-between">
        <div className="relative w-full sm:w-80">
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="جستجوی مشتری با نام، نام کاربری یا شماره تلفن..."
            className="w-full bg-slate-900 border border-slate-800 text-slate-100 rounded-xl pr-9 pl-4 py-2 text-xs focus:border-red-500 focus:outline-none placeholder-slate-500"
          />
          <Search className="w-4 h-4 text-slate-500 absolute right-3 top-2.5" />
        </div>

        <div className="text-xs text-slate-400">
          تعداد کل مشتریان: <span className="font-bold text-red-400">{customers.length} نفر</span>
        </div>
      </div>

      {/* Customers Cards Grid */}
      {filtered.length === 0 ? (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-12 text-center text-slate-500">
          <Users className="w-12 h-12 stroke-[1.2] text-slate-600 mx-auto mb-3" />
          <p className="text-sm font-medium text-slate-300">مشتری با این مشخصات یافت نشد.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filtered.map((c) => (
            <div
              key={c.id}
              className="bg-slate-900 border border-slate-800 hover:border-slate-700 rounded-2xl p-5 transition-all shadow-sm flex flex-col justify-between"
            >
              <div>
                <div className="flex items-start justify-between gap-2 mb-3">
                  <div>
                    <h3 className="text-base font-bold text-slate-100 leading-snug">{c.name}</h3>
                    <div className="flex items-center gap-1.5 text-xs text-red-400 font-mono mt-0.5" dir="ltr">
                      <span>@{c.username}</span>
                    </div>
                  </div>

                  <span className="text-[11px] font-semibold bg-slate-800 text-slate-300 px-2.5 py-1 rounded-full border border-slate-700 shrink-0">
                    {(c as any).projectsCount || 0} پروژه
                  </span>
                </div>

                {/* Login credentials box */}
                <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 mb-3 space-y-1.5 text-xs">
                  <div className="flex items-center justify-between text-slate-400">
                    <span className="flex items-center gap-1">
                      <KeyRound className="w-3.5 h-3.5 text-red-500" />
                      <span>رمز ورود مشتری:</span>
                    </span>
                    <span className="font-mono text-slate-200 font-bold bg-slate-900 px-2 py-0.5 rounded border border-slate-800" dir="ltr">
                      {c.password || `${solarYear}${c.username}`}
                    </span>
                  </div>

                  <div className="flex items-center justify-between text-slate-400">
                    <span className="flex items-center gap-1">
                      <Phone className="w-3.5 h-3.5 text-emerald-500" />
                      <span>شماره تماس:</span>
                    </span>
                    <span className="font-mono text-slate-200" dir="ltr">
                      {c.phone}
                    </span>
                  </div>

                  {c.address && (
                    <div className="flex items-start gap-1 text-[11px] text-slate-400 pt-1 border-t border-slate-800">
                      <MapPin className="w-3.5 h-3.5 text-slate-500 shrink-0 mt-0.5" />
                      <span className="truncate">{c.address}</span>
                    </div>
                  )}
                </div>
              </div>

              {/* Action buttons */}
              <div className="pt-3 border-t border-slate-800 flex items-center justify-between gap-2">
                <button
                  onClick={() => handleCopyCredentials(c)}
                  className={`flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg transition-colors cursor-pointer ${
                    copiedId === c.id
                      ? 'bg-emerald-950 text-emerald-300 border border-emerald-700/50'
                      : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700'
                  }`}
                  title="کپی پیامک اطلاعات ورود جهت ارسال به مشتری"
                >
                  {copiedId === c.id ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-400" />
                      <span>کپی شد!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5 text-slate-400" />
                      <span>کپی مشخصات ورود</span>
                    </>
                  )}
                </button>

                <div className="flex items-center gap-1">
                  <button
                    onClick={() => onSelectCustomerProjects(c.id)}
                    className="text-xs text-red-400 hover:text-red-300 font-semibold px-2 py-1.5 hover:bg-slate-800 rounded-lg transition-colors cursor-pointer"
                  >
                    پروژه‌ها
                  </button>

                  <button
                    onClick={() => {
                      if (confirm(`آیا از حذف مشتری "${c.name}" و تمام سفارشات مرتبط اطمینان دارید؟`)) {
                        onDeleteCustomer(c.id);
                      }
                    }}
                    className="p-1.5 text-slate-500 hover:text-rose-400 hover:bg-rose-950/30 rounded-lg transition-colors cursor-pointer"
                    title="حذف مشتری"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Modal: Create Customer */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 bg-slate-950/85 backdrop-blur-md flex items-center justify-center p-4 overflow-y-auto">
          <div className="w-full max-w-lg bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl p-6 relative max-h-[92vh] overflow-y-auto">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800 mb-4">
              <div className="flex items-center gap-2.5">
                <div className="p-2 rounded-xl bg-red-950/60 text-red-400 border border-red-800/60">
                  <UserPlus className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-base font-bold text-slate-100">
                    تعریف مشتری جدید
                  </h3>
                  <p className="text-xs text-slate-400">
                    تولید خودکار نام کاربری و پسورد اختصاصی
                  </p>
                </div>
              </div>
              <button
                onClick={() => setShowAddModal(false)}
                className="text-slate-400 hover:text-white"
              >
                ✕
              </button>
            </div>

            {createdResult ? (
              <div className="space-y-4 py-2">
                <div className="p-4 rounded-xl bg-emerald-950/50 border border-emerald-700/60 text-emerald-200 space-y-2">
                  <div className="flex items-center gap-2 font-bold text-sm">
                    <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                    <span>مشتری با موفقیت در سیستم ثبت گردید!</span>
                  </div>
                  <p className="text-xs text-emerald-300/90 leading-relaxed">
                    اطلاعات ورود زیر بر اساس فرمول (سال شمسی {solarYear} + نام‌کاربری) برای خریدار ایجاد شد:
                  </p>
                  <div className="bg-slate-950 p-3 rounded-lg border border-emerald-800/40 text-xs font-mono space-y-1.5 text-slate-200 text-left" dir="ltr">
                    <div><span className="text-slate-500">Name:</span> {createdResult.name}</div>
                    <div><span className="text-red-400">Username:</span> {createdResult.username}</div>
                    <div><span className="text-emerald-400 font-bold">Password:</span> {createdResult.password}</div>
                  </div>
                </div>

                <div className="flex gap-3">
                  <button
                    onClick={() => {
                      const text = `اطلاعات ورود به سامانه ساخت گاوصندوق فرنیو برای ${createdResult.name}:
نام کاربری: ${createdResult.username}
رمز عبور: ${createdResult.password}`;
                      navigator.clipboard.writeText(text);
                      alert('مشخصات در حافظه کپی شد.');
                    }}
                    className="flex-1 py-2.5 rounded-xl text-xs font-bold bg-slate-800 hover:bg-slate-700 text-slate-200 transition-colors flex items-center justify-center gap-1.5 cursor-pointer border border-slate-700"
                  >
                    <Copy className="w-3.5 h-3.5" />
                    <span>کپی اطلاعات ورود</span>
                  </button>

                  <button
                    onClick={() => setShowAddModal(false)}
                    className="flex-1 py-2.5 rounded-xl text-xs font-bold bg-red-600 hover:bg-red-700 text-white transition-all cursor-pointer"
                  >
                    بستن پنجره
                  </button>
                </div>
              </div>
            ) : (
              <form onSubmit={handleFormSubmit} className="space-y-4">
                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">
                    نام و نام خانوادگی / شرکت یا جواهری <span className="text-rose-400">*</span>
                  </label>
                  <input
                    id="new-customer-name"
                    type="text"
                    required
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="مثال: جناب آقای مهندس احمدی (صرافی صبا)"
                    className="w-full bg-slate-950 border border-slate-700 text-slate-100 rounded-xl px-3.5 py-2 text-xs sm:text-sm focus:border-red-500 focus:outline-none"
                  />
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      نام کاربری انگلیسی (Username) <span className="text-rose-400">*</span>
                    </label>
                    <input
                      id="new-customer-username"
                      type="text"
                      required
                      value={username}
                      onChange={(e) => setUsername(e.target.value)}
                      placeholder="مثلاً: ahmadi"
                      dir="ltr"
                      className="w-full bg-slate-950 border border-slate-700 text-slate-100 rounded-xl px-3 py-2 text-xs sm:text-sm font-mono text-left focus:border-red-500 focus:outline-none"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      شماره تماس مشتری <span className="text-rose-400">*</span>
                    </label>
                    <input
                      id="new-customer-phone"
                      type="text"
                      required
                      value={phone}
                      onChange={(e) => setPhone(e.target.value)}
                      placeholder="0912..."
                      dir="ltr"
                      className="w-full bg-slate-950 border border-slate-700 text-slate-100 rounded-xl px-3 py-2 text-xs sm:text-sm font-mono text-left focus:border-red-500 focus:outline-none"
                    />
                  </div>
                </div>

                {/* Password auto-generator preview */}
                <div className="p-3 bg-slate-950 rounded-xl border border-red-800/40 text-xs space-y-1.5">
                  <div className="flex items-center gap-1 text-red-400 font-bold">
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>تولید خودکار کلمه عبور طبق سال شمسی:</span>
                  </div>
                  <div className="flex items-center justify-between text-slate-300 bg-slate-900 p-2 rounded-lg font-mono border border-slate-800" dir="ltr">
                    <span className="text-red-400 font-bold">
                      {customPassword.trim() ? customPassword.trim() : autoGeneratedPassword}
                    </span>
                    <span className="text-[10px] text-slate-400 font-sans" dir="rtl">
                      {customPassword.trim() ? '(رمز سفارشی)' : `(سال شمسی ${solarYear} + نام کاربری)`}
                    </span>
                  </div>
                  <p className="text-[10px] text-slate-400">
                    خریدار پس از ثبت با همین نام کاربری و رمز وارد سامانه شده و مستندات مراحل ساخت را بررسی می‌کند.
                  </p>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">
                    رمز عبور دلخواه (اختیاری - در صورت تمایل به رمز اختصاصی)
                  </label>
                  <input
                    type="text"
                    value={customPassword}
                    onChange={(e) => setCustomPassword(e.target.value)}
                    placeholder="خالی بگذارید تا خودکار تولید شود"
                    dir="ltr"
                    className="w-full bg-slate-950 border border-slate-700 text-slate-100 rounded-xl px-3 py-2 text-xs font-mono text-left focus:border-red-500 focus:outline-none"
                  />
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">
                    آدرس محل تحویل یا نصب گاوصندوق
                  </label>
                  <input
                    type="text"
                    value={address}
                    onChange={(e) => setAddress(e.target.value)}
                    placeholder="شهر، خیابان، پلاک، طبقه..."
                    className="w-full bg-slate-950 border border-slate-700 text-slate-100 rounded-xl px-3.5 py-2 text-xs focus:border-red-500 focus:outline-none"
                  />
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">
                    یادداشت‌های اختصاصی مدیر
                  </label>
                  <textarea
                    rows={2}
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    placeholder="توضیحات تکمیلی..."
                    className="w-full bg-slate-950 border border-slate-700 text-slate-100 rounded-xl px-3.5 py-2 text-xs focus:border-red-500 focus:outline-none"
                  />
                </div>

                <div className="pt-2 flex gap-3">
                  <button
                    type="button"
                    onClick={() => setShowAddModal(false)}
                    className="flex-1 py-2.5 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors cursor-pointer border border-slate-700"
                  >
                    انصراف
                  </button>

                  <button
                    id="submit-create-customer-btn"
                    type="submit"
                    disabled={submitting}
                    className="flex-1 py-2.5 rounded-xl text-xs font-bold bg-red-600 hover:bg-red-700 text-white transition-all shadow-md shadow-red-950/50 flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50"
                  >
                    {submitting ? (
                      <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    ) : (
                      <>
                        <UserPlus className="w-4 h-4" />
                        <span>ثبت مشتری و صدور دسترسی</span>
                      </>
                    )}
                  </button>
                </div>
              </form>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
